import { db, categoriesTable, usersTable, jobsTable, startupIdeasTable } from "@workspace/db";

async function seed() {
  console.log("Seeding database...");

  await db.insert(categoriesTable).values([
    { name: "Technology & Software", slug: "technology", description: "Tech startups, SaaS, apps, platforms", icon: "💻" },
    { name: "Food & Beverage", slug: "food", description: "Restaurants, cafes, catering, food delivery", icon: "🍕" },
    { name: "Retail & E-commerce", slug: "retail", description: "Physical stores, online shops, marketplaces", icon: "🛍️" },
    { name: "Health & Fitness", slug: "health", description: "Gyms, wellness centers, medical services", icon: "🏋️" },
    { name: "Education & Training", slug: "education", description: "Schools, tutoring, online courses, bootcamps", icon: "📚" },
    { name: "Consulting & Professional Services", slug: "consulting", description: "Business, legal, financial consulting", icon: "💼" },
    { name: "Real Estate", slug: "real-estate", description: "Property development, rentals, agencies", icon: "🏠" },
    { name: "Marketing & Creative", slug: "marketing", description: "Agencies, design studios, content creation", icon: "🎨" },
    { name: "Logistics & Delivery", slug: "logistics", description: "Shipping, warehousing, last-mile delivery", icon: "🚚" },
    { name: "Beauty & Personal Care", slug: "beauty", description: "Salons, spas, cosmetics brands", icon: "💄" },
    { name: "Manufacturing & Production", slug: "manufacturing", description: "Product manufacturing, fabrication", icon: "🏭" },
    { name: "Travel & Hospitality", slug: "travel", description: "Hotels, tourism, experiences, transport", icon: "✈️" },
  ]).onConflictDoNothing();

  await db.insert(usersTable).values([
    { name: "Admin User", email: "admin@venturewise.io", role: "admin" },
    { name: "Sarah Johnson", email: "sarah@techventures.com", role: "user" },
    { name: "Michael Chen", email: "m.chen@startupstudio.co", role: "user" },
    { name: "Aisha Rahman", email: "aisha.r@bizlaunch.io", role: "user" },
    { name: "Carlos Mendez", email: "carlos@growthlab.co", role: "user" },
  ]).onConflictDoNothing();

  await db.insert(jobsTable).values([
    {
      title: "Senior Full-Stack Developer",
      company: "TechVentures Inc.",
      location: "San Francisco, CA",
      type: "full-time",
      category: "Technology",
      description: "Join our fast-growing fintech startup as a Senior Full-Stack Developer. You'll architect and build scalable systems serving millions of users globally.",
      requirements: "5+ years experience with React, Node.js/TypeScript, PostgreSQL. Experience with cloud infrastructure (AWS/GCP). Strong system design skills. Fintech experience a plus.",
      salaryMin: "150000",
      salaryMax: "220000",
      experienceLevel: "senior",
      isActive: true,
      applicantCount: 47,
    },
    {
      title: "Marketing Manager",
      company: "GrowthLab",
      location: "New York, NY",
      type: "full-time",
      category: "Marketing",
      description: "Lead our marketing team in developing and executing data-driven campaigns that drive user acquisition and brand growth across digital channels.",
      requirements: "4+ years in B2B/B2C marketing. Expertise in paid social, SEO, email marketing, and content strategy. Strong analytical skills and data-driven mindset.",
      salaryMin: "90000",
      salaryMax: "130000",
      experienceLevel: "mid",
      isActive: true,
      applicantCount: 83,
    },
    {
      title: "Business Development Representative",
      company: "Nexus Capital",
      location: "Austin, TX",
      type: "full-time",
      category: "Sales",
      description: "Drive new business by identifying and qualifying investment opportunities, building relationships with founders, and growing our deal pipeline.",
      requirements: "2+ years in sales or business development. Excellent communication skills. Experience in startup ecosystem preferred. CRM proficiency required.",
      salaryMin: "60000",
      salaryMax: "90000",
      experienceLevel: "entry",
      isActive: true,
      applicantCount: 124,
    },
    {
      title: "Product Manager",
      company: "InnovatePro",
      location: "Remote",
      type: "remote",
      category: "Product",
      description: "Own the product roadmap for our AI-powered analytics platform. Work closely with engineering, design, and customers to ship features users love.",
      requirements: "3+ years PM experience at B2B SaaS companies. Strong data analysis skills. Experience with Agile/Scrum. Customer-facing communication skills essential.",
      salaryMin: "120000",
      salaryMax: "175000",
      experienceLevel: "mid",
      isActive: true,
      applicantCount: 61,
    },
    {
      title: "Financial Analyst",
      company: "Meridian Ventures",
      location: "Chicago, IL",
      type: "full-time",
      category: "Finance",
      description: "Analyze investment opportunities, build financial models, and support our venture partners in making high-quality investment decisions.",
      requirements: "Bachelor's or Master's in Finance/Economics. 2+ years in investment banking, PE, or VC. Exceptional Excel and financial modeling skills. CFA a plus.",
      salaryMin: "80000",
      salaryMax: "120000",
      experienceLevel: "entry",
      isActive: true,
      applicantCount: 95,
    },
    {
      title: "Chief Operating Officer",
      company: "ScaleUp Solutions",
      location: "Boston, MA",
      type: "full-time",
      category: "Executive",
      description: "Join as COO to help scale our operations from $10M to $100M ARR. You'll lead operations, HR, and business systems across a 50-person organization.",
      requirements: "10+ years of operational leadership experience. Proven track record scaling teams and processes at growth-stage companies. MBA preferred.",
      salaryMin: "250000",
      salaryMax: "350000",
      experienceLevel: "executive",
      isActive: true,
      applicantCount: 18,
    },
    {
      title: "UX/UI Designer",
      company: "DesignFirst Studio",
      location: "Seattle, WA",
      type: "contract",
      category: "Design",
      description: "Design beautiful, intuitive user experiences for our portfolio of B2B SaaS products. Work directly with founders and users to solve real problems.",
      requirements: "Portfolio demonstrating product design excellence. Proficiency in Figma. Strong understanding of design systems and accessibility standards.",
      salaryMin: "80",
      salaryMax: "130",
      experienceLevel: "mid",
      isActive: true,
      applicantCount: 72,
    },
    {
      title: "Data Science Intern",
      company: "AI Ventures",
      location: "Remote",
      type: "internship",
      category: "Technology",
      description: "Work with our machine learning team to develop predictive models, analyze large datasets, and contribute to AI-powered product features.",
      requirements: "Currently enrolled in Computer Science, Statistics, or related program. Experience with Python, pandas, scikit-learn. Portfolio of personal ML projects.",
      salaryMin: "25",
      salaryMax: "35",
      experienceLevel: "entry",
      isActive: true,
      applicantCount: 210,
    },
  ]).onConflictDoNothing();

  await db.insert(startupIdeasTable).values([
    {
      title: "AI-Powered B2B Lead Generation Platform",
      description: "An intelligent platform that uses AI to identify, score, and engage high-quality B2B leads automatically. Integrates with CRMs and automates personalized outreach at scale, reducing customer acquisition costs by 60%.",
      category: "Technology",
      requiredBudget: "250000",
      expectedReturn: "1500000",
      riskLevel: "Medium",
      stage: "mvp",
      isActive: true,
    },
    {
      title: "Sustainable Urban Vertical Farming Network",
      description: "A network of hydroponic vertical farms in urban centers supplying fresh, local produce to restaurants and grocery stores. Zero pesticides, 95% less water usage, and year-round production regardless of weather.",
      category: "Food & Agriculture",
      requiredBudget: "800000",
      expectedReturn: "3200000",
      riskLevel: "Medium",
      stage: "idea",
      isActive: true,
    },
    {
      title: "Mental Health & Wellness Super-App",
      description: "A comprehensive mental health platform combining AI therapy chatbots, licensed therapist video sessions, guided meditation, mood tracking, and peer support communities. HIPAA-compliant with insurance integration.",
      category: "Health & Wellness",
      requiredBudget: "400000",
      expectedReturn: "2800000",
      riskLevel: "Low",
      stage: "mvp",
      isActive: true,
    },
    {
      title: "Blockchain-Based Supply Chain Transparency Tool",
      description: "Enterprise solution that tracks product provenance from raw material to consumer using blockchain. Helps brands prove sustainability claims, reduce fraud, and comply with upcoming EU supply chain regulations.",
      category: "Technology",
      requiredBudget: "600000",
      expectedReturn: "4000000",
      riskLevel: "High",
      stage: "idea",
      isActive: true,
    },
    {
      title: "Premium Co-Working Space Chain for Creatives",
      description: "Boutique co-working spaces designed specifically for creative professionals — photographers, designers, filmmakers, and musicians. Equipped with professional equipment, green screens, podcast studios, and editing suites.",
      category: "Real Estate & Workspace",
      requiredBudget: "1200000",
      expectedReturn: "4800000",
      riskLevel: "Medium",
      stage: "growth",
      isActive: true,
    },
    {
      title: "EdTech Platform for Trade Skills Training",
      description: "Online and AR-assisted training platform for high-demand trade skills: electricians, plumbers, HVAC technicians, and welders. Addresses the skilled trades shortage with gamified learning and job placement services.",
      category: "Education",
      requiredBudget: "350000",
      expectedReturn: "2100000",
      riskLevel: "Low",
      stage: "mvp",
      isActive: true,
    },
    {
      title: "Micro-Mobility Fleet Management SaaS",
      description: "B2B SaaS platform for managing fleets of e-bikes, scooters, and shared vehicles. Features real-time tracking, predictive maintenance, dynamic pricing, and compliance tools for city permits.",
      category: "Transportation",
      requiredBudget: "500000",
      expectedReturn: "3500000",
      riskLevel: "High",
      stage: "scaling",
      isActive: true,
    },
    {
      title: "D2C Personalized Nutrition Brand",
      description: "Science-backed, personalized nutrition subscription brand using DNA and blood biomarker data to create custom supplement stacks, meal plans, and health coaching. Subscriptions from $79/month.",
      category: "Health & Wellness",
      requiredBudget: "300000",
      expectedReturn: "1800000",
      riskLevel: "Medium",
      stage: "idea",
      isActive: true,
    },
  ]).onConflictDoNothing();

  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seeding failed:", err);
  process.exit(1);
});
